// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXpak_kBrWGZRDA2cQuQhL0evUKpVBuDw',
    appId: '1:792661918201:web:278d34d9162541d65ffd28',
    messagingSenderId: '792661918201',
    projectId: 'task-4d248',
    authDomain: 'task-4d248.firebaseapp.com',
    storageBucket: 'task-4d248.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWyt5YC03jlq9YBcHlhOROFd3rW452Tn4',
    appId: '1:792661918201:android:ee54b5d797875af65ffd28',
    messagingSenderId: '792661918201',
    projectId: 'task-4d248',
    storageBucket: 'task-4d248.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjy_menQKIG8PBOgcGtSjkTJeW-NVRhQc',
    appId: '1:792661918201:ios:23b21d5f791e74bd5ffd28',
    messagingSenderId: '792661918201',
    projectId: 'task-4d248',
    storageBucket: 'task-4d248.appspot.com',
    iosBundleId: 'com.example.googleSign',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjy_menQKIG8PBOgcGtSjkTJeW-NVRhQc',
    appId: '1:792661918201:ios:0ab9fdada5d6b0715ffd28',
    messagingSenderId: '792661918201',
    projectId: 'task-4d248',
    storageBucket: 'task-4d248.appspot.com',
    iosBundleId: 'com.example.googleSign.RunnerTests',
  );
}
